### PR TITLE
Search for also places that correspond to addr:street

### PR DESCRIPTION
**Pull request by johsin18**
This is a PR to solve issue #111.

All commits but the last are cleanup and refactoring.

I tested only using osmi-testzone.osm, and I ran it once on the Swiss data set.  I was not able to test the results graphically (probably involves some huge setup).
Can somebody please test it graphically, e.g. the addresses around Tellplatz Basel should not be shown red anymore:
http://tools.geofabrik.de/osmi/?view=addresses&lon=7.59483&lat=47.54331&zoom=17&overlays=buildings,buildings_with_addresses,postal_code,entrances_deprecated,entrances,street_not_found,interpolation,interpolation_errors,connection_lines,nearest_points,nearest_roads,nearest_areas,addrx_on_nonclosed_way

### CODE REVIEW

**Comment by johsin18** [comment]
@ltog @Nakaner I would appreciate your comments.

**Comment by ltog** [comment]
@johsin18 (CC @Nakaner ): Thank you for taking the time to write the pull request and sorry for the delayed answer. I started working on a file for [Vagrant](https://en.wikipedia.org/wiki/Vagrant_(software)) to resolve your mentioned

>  I was not able to test the results graphically (probably involves some huge setup).

by providing a one-click solution to setup osmi-addresses. While preparing the Vagrantfile I discovered some issues with the GDAL version provided by Ubuntu 18.04 which I began to address here: https://github.com/ltog/osmi-addresses/commits/gdal_fix

I'll be at [SotM](https://2018.stateofthemap.org/) next weekend. If you'll be there too, we could meet.

**Comment by johsin18** [comment]
So finally I was able to set up MapServer and test my changes on the map. Following the README, it was less hard than expected.  I though I would have to also set up a server serving the base tile layers, but that's not needed, fortunately.

So indeed my code was still buggy, but that should be fixed now.

I would appreciate if you would merge my branch.

**Comment by ltog** [comment]
@johsin18 : I'm glad the README was helpful...

Recently I met with @Nakaner . We weren't sure if tying together `addr:street=*` with `place=square, name=*` is something we should encourage through osmi-addresses. We therefore decided to ask for a broader opinion at the tagging mailinglist. You can find my message at https://lists.openstreetmap.org/pipermail/tagging/2018-August/038415.html . The whole structure of the discussion will be visible at https://lists.openstreetmap.org/pipermail/tagging/2018-August/thread.html once it took place.

Sorry, that this takes so long...

**Comment by Nakaner** [comment]
Thank you for your contribution.

I decided to merge this pull request (not the refactoring only) because there are indeed cases where `place=square` looks unavoidable to me. The Tellplatz example in Basel is not such a case because it would be possible to name the pedestrian areas.

**Comment by ltog** [comment]
@Nakaner : Thank you for taking care of this!

**Comment by Nakaner** [comment]
The Mapserver styles have been deployed now.

**Comment by johsin18** [comment]
Thanks for taking this in.

**Pull request merged**
